package message

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/soasurs/adk/model"
)

// ToolCall represents a persisted tool call within an assistant message.
type ToolCall struct {
	// ID is the unique identifier of this tool call, matching model.ToolCall.ID.
	ID        string `json:"id" db:"id"`
	Name      string `json:"name" db:"name"`
	Arguments string `json:"arguments" db:"arguments"`
}

// ToolCalls is a slice of ToolCall that serializes to/from JSON for database storage.
type ToolCalls []ToolCall

// Value implements driver.Valuer so ToolCallList can be written to the database as a JSON string.
func (tl ToolCalls) Value() (driver.Value, error) {
	b, err := json.Marshal(tl)
	if err != nil {
		return nil, err
	}
	return string(b), nil
}

// Scan implements sql.Scanner so ToolCallList can be read from the database from a JSON string.
func (tl *ToolCalls) Scan(src any) error {
	if src == nil {
		*tl = ToolCalls{}
		return nil
	}
	var s string
	switch v := src.(type) {
	case string:
		s = v
	case []byte:
		s = string(v)
	default:
		return fmt.Errorf("message: unsupported ToolCallList source type: %T", src)
	}
	return json.Unmarshal([]byte(s), tl)
}

// Message represents a persisted conversation message.
type Message struct {
	MessageID int64  `json:"message_id" db:"message_id"`
	SessionID int64  `json:"session_id" db:"session_id"`
	Role      string `json:"role" db:"role"`
	// Name optionally identifies the producer of this message (e.g. an agent name).
	Name    string `json:"name" db:"name"`
	Content string `json:"content" db:"content"`
	// ReasoningContent stores the model's chain-of-thought output when provided.
	ReasoningContent string    `json:"reasoning_content" db:"reasoning_content"`
	ToolCalls        ToolCalls `json:"tool_calls" db:"tool_calls"`
	// ToolCallID links a tool-role message back to the assistant's ToolCall.ID it responds to.
	ToolCallID string `json:"tool_call_id" db:"tool_call_id"`
	// PromptTokens is the number of input tokens consumed by the LLM call that produced this message.
	PromptTokens int64 `json:"prompt_tokens" db:"prompt_tokens"`
	// CompletionTokens is the number of output tokens generated by the LLM call.
	CompletionTokens int64 `json:"completion_tokens" db:"completion_tokens"`
	// TotalTokens is the sum of PromptTokens and CompletionTokens.
	TotalTokens int64 `json:"total_tokens" db:"total_tokens"`
	CreatedAt   int64 `json:"created_at" db:"created_at"`
	UpdatedAt   int64 `json:"updated_at" db:"updated_at"`
	// CompactedAt is set when the message has been archived by a CompactMessages call.
	// A non-zero value means the message is compacted and no longer part of the active history.
	CompactedAt int64 `json:"compacted_at" db:"compacted_at"`
	DeletedAt   int64 `json:"deleted_at" db:"deleted_at"`
}

// ToModel converts a persisted Message to a model.Message for LLM consumption.
func (m *Message) ToModel() model.Message {
	toolCalls := make([]model.ToolCall, len(m.ToolCalls))
	for i, tc := range m.ToolCalls {
		toolCalls[i] = model.ToolCall{
			ID:        tc.ID,
			Name:      tc.Name,
			Arguments: tc.Arguments,
		}
	}
	msg := model.Message{
		Role:             model.Role(m.Role),
		Name:             m.Name,
		Content:          m.Content,
		ReasoningContent: m.ReasoningContent,
		ToolCalls:        toolCalls,
		ToolCallID:       m.ToolCallID,
	}
	if m.PromptTokens != 0 || m.CompletionTokens != 0 || m.TotalTokens != 0 {
		msg.Usage = &model.TokenUsage{
			PromptTokens:     m.PromptTokens,
			CompletionTokens: m.CompletionTokens,
			TotalTokens:      m.TotalTokens,
		}
	}
	return msg
}

// FromModel creates a Message from a model.Message, ready for persistence.
// MessageID and timestamp fields must be set by the caller before saving.
func FromModel(m model.Message) *Message {
	toolCalls := make(ToolCalls, len(m.ToolCalls))
	for i, tc := range m.ToolCalls {
		toolCalls[i] = ToolCall{
			ID:        tc.ID,
			Name:      tc.Name,
			Arguments: tc.Arguments,
		}
	}
	msg := &Message{
		Role:             string(m.Role),
		Name:             m.Name,
		Content:          m.Content,
		ReasoningContent: m.ReasoningContent,
		ToolCalls:        toolCalls,
		ToolCallID:       m.ToolCallID,
	}
	if m.Usage != nil {
		msg.PromptTokens = m.Usage.PromptTokens
		msg.CompletionTokens = m.Usage.CompletionTokens
		msg.TotalTokens = m.Usage.TotalTokens
	}
	return msg
}
